services:
  web:
    build: .
    develop:
      watch:
        - action: sync
          path: .
          target: /var/data/web
          ignore:
            - node_modules
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"
    restart: always
    networks:
      - frontend
