services:
  db:
    extends:
      file: ./db/docker-compose.yaml
      service: db
    networks:
      - backend

  api:
    extends:
      file: ./api/docker-compose.yaml
      service: api
    depends_on:
      - db
    networks:
      - backend

  web:
    extends:
      file: ./client/docker-compose.yaml
      service: web
    depends_on:
      - api
    networks:
      - frontend

networks:
  backend:
  frontend:
