services:
  db:
    extends:
      file: ./db/docker-compose.yaml
      service: db

  api:
    extends:
      file: ./api/docker-compose.yaml
      service: api
  web:
    extends:
      file: ./client/docker-compose.yaml
      service: web
