services:
  db:
    extends:
      file: ./db/docker-compose.yaml
      service: db

  api:
    extends:
      file: ./api/docker-compose.yaml
      service: api
    depends_on:
      - db

  # web:
  #   extends:
  #     file: ./client/docker-compose.yaml
  #     service: web
  #   depends_on:
  #     - api

networks:
  backend:
  frontend:
