import northFaceLogo from "@/assets/north-face-logo.svg";
import ProductExample from "@/assets/product-example.avif";

export const mensJackets = {
  ["men's-jackets"]: [
    {
      id: 1000,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1001,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1002,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1003,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1004,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1005,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1006,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
    {
      id: 1007,
      title: "Hydrenalite™ Down Hoodie",
      logoText: "The North Face",
      logoImgSrc: northFaceLogo,
      description: "",
      sex: "Men's",
      productImgSrc: ProductExample,
    },
  ],
};
