import northFaceLogo from "@/assets/north-face-logo.svg";
import ProductExample from "@/assets/product-example.avif";
import { CategoryDataRaw } from "@/types/types";

export const mensJackets: CategoryDataRaw = {
  ["mens-jackets"]: {
    metadata: {
      brandName: "The North Face",
      categoryName: "Men's Jackets",
      categoryId: "mens-jackets",
    },
    products: [
      {
        id: 1008,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1000,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1001,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1002,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1003,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1004,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1005,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1006,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
      {
        id: 1007,
        title: "Hydrenalite™ Down Hoodie",
        logoText: "The North Face",
        logoImgSrc: northFaceLogo,
        description: "",
        sex: "Men's",
        productImgSrc: ProductExample,
        type: "rain",
      },
    ],
  },
};
