services:
  db:
    image: postgres
    restart: always
    container_name: AT
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: approach_trail
    ports:
      - "5432:5432"
