services:
  db:
    image: postgres
    restart: always
    container_name: ApproachTrailDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: approach_trail
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
