services:
  db:
    image: postgres
    restart: always
    container_name: AT
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: approach_trail
