services:
  api:
    build:
      context: .
    develop:
      watch:
        - action: sync
          path: .
          target: /var/data/api
          ignore:
            - node_modules
    ports:
      - "3000:3000"
    restart: always
